### ISSUE TITLE
Juniper compatibility

### ISSUE THREAD

**Issue by toxinu** [edx-solutions/xblock-drag-and-drop-v2#241]
Hi there,

I wanted to know if `xblock-drag-and-drop-v2` xBlock is already Juniper (Python 3 and Django 2.2) compatible and if not, is there any plan to update it for Juniper? Or are you open to contributions?

Thanks.

cc @davidjoy @AhtishamShahid

**Comment by davidjoy** [comment]
Hi @toxinu,

To our knowledge there are no compatibility issues with Python 3 and Django 2.2 for this XBlock.  (It's currently running with both in production on https://edx.org, for instance)

If you're aware of any, we're certainly open to contributions and/or new Issues. 👍 

Thanks!

**Comment by toxinu** [comment]
@davidjoy Perfect! Thanks for your answer :)
